name: Test Workflow
on: [push, pull_request]
env:
  LLVM_VERSION: 18
jobs:
  debug:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cpp_version: [14, 17, 20]
        toolchain: ['clang', 'gcc']
        include:
          - toolchain: gcc
            c-compiler: gcc
            cxx-compiler: g++
          - toolchain: clang
            c-compiler: clang
            cxx-compiler: clang++
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh $LLVM_VERSION
          sudo apt update -y && sudo apt upgrade -y
          sudo apt-get -y install gcc-multilib g++-multilib ninja-build clang-tidy-$LLVM_VERSION
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-$LLVM_VERSION 50
          clang-tidy --version
      - run: |
          cmake --version
          cmake --preset OCVSMD-Linux -DCMAKE_CXX_STANDARD=${{ matrix.cpp_version }} -DCMAKE_C_COMPILER=${{ matrix.c-compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx-compiler }}
          cmake --build --preset OCVSMD-Linux-Debug
          ctest --preset OCVSMD-Debug
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{github.job}}_cpp${{ matrix.cpp_version }}_${{matrix.toolchain}}
          path: ${{github.workspace}}/**/*
          retention-days: 2

  optimizations:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cpp_version: [14, 17, 20]
        toolchain: ['clang', 'gcc']
        build_type: [Release, MinSizeRel]
        include:
          - toolchain: gcc
            c-compiler: gcc
            cxx-compiler: g++
          - toolchain: clang
            c-compiler: clang
            cxx-compiler: clang++
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install gcc-multilib g++-multilib ninja-build 
      - run: |
          cmake --version
          cmake --preset OCVSMD-Linux -DCMAKE_CXX_STANDARD=${{ matrix.cpp_version }} -DCMAKE_C_COMPILER=${{ matrix.c-compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx-compiler }}
          cmake --build --preset OCVSMD-Linux-Release
          ctest --preset OCVSMD-Release
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{github.job}}_cpp${{ matrix.cpp_version }}_${{matrix.toolchain}}_${{matrix.build_type}}
          path: ${{github.workspace}}/**/*
          retention-days: 2

  style_check:
    if: false #âž• Disable for now
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: './test ./src'
          extensions: 'c,h,cpp,hpp'
          clangFormatVersion: ${{ env.LLVM_VERSION }}
